### ISSUE TITLE
HttpError: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#list-issue-comments

### ISSUE THREAD

**Issue by filip-michalsky** [braintrustdata/eval-action#34]
cannot use this - it does not work.

**Comment by ankrgyl** [comment]
See the permissions note in the [docs](https://www.braintrust.dev/docs/guides/evals/run#github-action). Make sure to add the following to your action:

```
name: "Run Evals"
---
permissions:
  pull-requests: write
  contents: read
```
