### ISSUE TITLE
Only Node.js supported error

### ISSUE THREAD

**Issue by ramon-prieto** [braintrustdata/eval-action#41]
# Description
## Issue Summary
When trying to run the Braintrust eval-action with runtime: python in our GitHub workflow, the action fails with the error message:
supported

```
Error: Only Node.js runtime is supported
```

This contradicts the documentation which states that both Node.js and Python runtimes are supported options.

## Steps to reproduce

1. Set up a GitHub workflow that uses the Braintrust eval-action
2. Configure the action with runtime: python
3. Run the workflow

### Configuration

Here's the relevant section from our workflow file:

```yaml
- name: Run Patient Matcher Evaluations
  if: github.event_name == 'pull_request'
  uses: braintrustdata/eval-action@v1
  with:
    api_key: ${{ secrets.BRAINTRUST_API_KEY }}
    runtime: python
    root: trially_agents/trially_agents/evals
    paths: |
      run.py
```

## Expected Behavior

The action should recognize and support the Python runtime as indicated in the README documentation:
> You can configure the following variables:
> * runtime: Either node or python

## Actual Behavior
The action fails with the error message: 

```
Error: Only Node.js runtime is supported
```

## Environment
- braintrustdata/eval-action version: v1
- Python 3.12

Questions
- Is Python runtime support actually implemented in the current release?
- If not, is there an estimated timeline for when Python support will be available?
- In the meantime, is there a workaround to run Python-based evals with this action?

Thank you for your help!
